"""update tables

Revision ID: adff77b5fda5
Revises: 
Create Date: 2023-11-30 19:43:36.334855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adff77b5fda5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_name', sa.String(), nullable=True),
    sa.Column('movie_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], name=op.f('fk_movies_genre_id_genres')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_movies_user_id_users')),
    sa.PrimaryKeyConstraint('movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    op.drop_table('users')
    op.drop_table('genres')
    # ### end Alembic commands ###
